apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vmtips-data
  # namespace: default   # avkommentera och ändra om du använder annan namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
